backend:
  name: github
  repo: CoreyGinnivan/urbanplate # Path to your GitHub repository
  branch: master # Branch to update (master by default)

public_folder: "images/recipes" # Folder where user uploaded files should go
media_folder: "images/recipes" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "recipes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "New Recipe" # Used in the UI, ie.: "New Post"
    folder: "source/recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: frontmatter
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}